spring:
  application:
    name: yuapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuapi
    username: root
    password: 168602
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# SDK
yuapi:
  client:
    access-key: chouchou
    secret-key: shangyingzhi

dubbo:
  application:
    qos-enable: false
    pos-accept-foreign-ip: false
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
    port: -1
  # 配置注册中心
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
  # 设置协议-协议由提供方指定消费方被动接受
    protocol:
      name: duboo
      port: 20882

